title: Eduardo Anica Gonzalez - Data Analyst Portfolio
#logo: /assets/img/logo.png
description: MEduardo Anica Gonzalez is a Data Analyst with passion for the power of data in the modern world.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
